# build & run locally with:
#   cd "$(git rev-parse --show-toplevel)"
#   CGO_ENABLED=0 go build -o anonbird ./client
#   podman build --build-arg TARGETPLATFORM=. -t localhost/anonbird:latest -f client/Dockerfile-rootless --ignorefile .dockerignore-client .
#   podman run --rm -it --cap-add={BPF,NET_ADMIN,NET_RAW} localhost/anonbird:latest

FROM alpine:3.22.0

RUN apk add --no-cache \
      bash \
      ca-certificates \
    && adduser -D -h /var/lib/anonbird anonbird

WORKDIR /var/lib/anonbird
USER anonbird:anonbird

ENV \
    ANONBIRD_BIN="/usr/local/bin/anonbird" \
    NB_USE_NETSTACK_MODE="true" \
    NB_ENABLE_NETSTACK_LOCAL_FORWARDING="true" \
    NB_CONFIG="/var/lib/anonbird/config.json" \
    NB_STATE_DIR="/var/lib/anonbird" \
    NB_DAEMON_ADDR="unix:///var/lib/anonbird/anonbird.sock" \
    NB_LOG_FILE="console,/var/lib/anonbird/client.log" \
    NB_DISABLE_DNS="true" \
    NB_ENABLE_CAPTURE="false" \
    NB_ENTRYPOINT_SERVICE_TIMEOUT="30"

ENTRYPOINT [ "/usr/local/bin/anonbird-entrypoint.sh" ]

ARG TARGETPLATFORM
ARG ANONBIRD_BINARY=anonbird
COPY client/anonbird-entrypoint.sh /usr/local/bin/anonbird-entrypoint.sh
COPY ${TARGETPLATFORM}/${ANONBIRD_BINARY} /usr/local/bin/anonbird
