#!/bin/sh

set -x

APP=/Applications/AnonBird.app
AGENT=/usr/local/bin/anonbird
LOG_FILE=/var/log/anonbird/client_post_install.log

mkdir -p /var/log/anonbird/
mkdir -p /usr/local/bin/

{
    echo "Installing AnonBird..."

    if test -d $APP; then
        echo "AnonBird app copied successfully."
    else
        echo "AnonBird app could not be copied to the Applications folder."
        exit 1
    fi

    ln -fs $APP/Contents/MacOS/anonbird $AGENT
    if test -f $AGENT; then
        echo "AnonBird binary linked successfully."
    else
        echo "AnonBird could not create symlink to /usr/local/bin"
        exit 1
    fi

    $AGENT service install || true
    $AGENT service start || true

    open $APP

    echo "Finished AnonBird installation successfully"
    exit 0 # all good
} &> $LOG_FILE
