#!/bin/sh

set -x

LOG_FILE=/var/log/anonbird/client_pre_install.log
AGENT=/usr/local/bin/anonbird

mkdir -p /var/log/anonbird/

{
    # check if it was installed with brew
    brew list --formula | grep anonbird
    if [ $? -eq 0 ]
    then
        echo "AnonBird has been installed with Brew. Please use Brew to update the package."
        exit 1
    fi
    osascript -e 'quit app "AnonBird"' || true
    $AGENT service stop || true

    echo "Preinstall complete"
    exit 0 # all good
} &> $LOG_FILE
