version: 2

project_name: anonbird
builds:
  - id: anonbird-wasm
    dir: client/wasm/cmd
    binary: anonbird
    env: [GOOS=js, GOARCH=wasm, CGO_ENABLED=0]
    goos:
      - js
    goarch:
      - wasm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird
    dir: client
    binary: anonbird
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm
      - amd64
      - arm64
      - 386
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - load_wgnt_from_rsrc

  - id: anonbird-static
    dir: client
    binary: anonbird
    env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - load_wgnt_from_rsrc

  - id: anonbird-mgmt
    dir: management
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Runtime.Goos "linux" }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm"}}CC=arm-linux-gnueabihf-gcc{{- end }}
        {{- end }}
    binary: anonbird-mgmt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-signal
    dir: signal
    env: [CGO_ENABLED=0]
    binary: anonbird-signal
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-relay
    dir: relay
    env: [CGO_ENABLED=0]
    binary: anonbird-relay
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-server
    dir: combined
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Runtime.Goos "linux" }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm"}}CC=arm-linux-gnueabihf-gcc{{- end }}
        {{- end }}
    binary: anonbird-server
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-upload
    dir: upload-server
    env: [CGO_ENABLED=0]
    binary: anonbird-upload
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-proxy
    dir: proxy/cmd/proxy
    env: [CGO_ENABLED=0]
    binary: anonbird-proxy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.Commit={{.Commit}} -X main.BuildDate={{.CommitDate}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: anonbird-idp-migrate
    dir: tools/idp-migrate
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Runtime.Goos "linux" }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
          {{- if eq .Arch "arm"}}CC=arm-linux-gnueabihf-gcc{{- end }}
        {{- end }}
    binary: anonbird-idp-migrate
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/netbirdio/netbird/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - id: anonbird

archives:
  - ids:
      - anonbird
      - anonbird-static
  - id: anonbird-wasm
    ids:
      - anonbird-wasm
    name_template: "{{ .ProjectName }}_{{ .Version }}"
    formats:
      - binary
  - id: anonbird-idp-migrate
    ids:
      - anonbird-idp-migrate
    name_template: "anonbird-idp-migrate_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - maintainer: AnonBird <dev@anonbird.local>
    description: AnonBird client.
    homepage: https://github.com/Cr0me1ve/anonbird
    license: BSD-3-Clause
    id: anonbird_deb
    package_name: anonbird
    bindir: /usr/bin
    ids:
      - anonbird
    formats:
      - deb
    scripts:
      postinstall: "release_files/post_install.sh"
      preremove: "release_files/pre_remove.sh"

  - maintainer: AnonBird <dev@anonbird.local>
    description: AnonBird client.
    homepage: https://github.com/Cr0me1ve/anonbird
    license: BSD-3-Clause
    id: anonbird_rpm
    package_name: anonbird
    bindir: /usr/bin
    ids:
      - anonbird
    formats:
      - rpm
    scripts:
      postinstall: "release_files/post_install.sh"
      preremove: "release_files/pre_remove.sh"
    rpm:
      signature:
        key_file: '{{ if index .Env "GPG_RPM_KEY_FILE" }}{{ .Env.GPG_RPM_KEY_FILE }}{{ end }}'

dockers_v2:
  - id: anonbird
    ids:
      - anonbird
    dockerfile: client/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird
    tags:
      - "{{ .Version }}"
      - latest
    extra_files:
      - client/anonbird-entrypoint.sh
    labels: &oci_labels
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.source": "https://github.com/Cr0me1ve/anonbird"
      maintainer: dev@anonbird.local
    platforms: &linux_platforms
      - linux/amd64
      - linux/arm64

  - id: anonbird-rootless
    ids:
      - anonbird
    dockerfile: client/Dockerfile-rootless
    images:
      - ghcr.io/cr0me1ve/anonbird
    tags:
      - "{{ .Version }}-rootless"
      - rootless-latest
    extra_files:
      - client/anonbird-entrypoint.sh
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-relay
    ids:
      - anonbird-relay
    dockerfile: relay/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-relay
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-signal
    ids:
      - anonbird-signal
    dockerfile: signal/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-signal
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-management
    ids:
      - anonbird-mgmt
    dockerfile: management/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-management
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-management-debug
    ids:
      - anonbird-mgmt
    dockerfile: management/Dockerfile.debug
    images:
      - ghcr.io/cr0me1ve/anonbird-management
    tags:
      - "{{ .Version }}-debug"
      - debug-latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-upload
    ids:
      - anonbird-upload
    dockerfile: upload-server/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-upload
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-server
    ids:
      - anonbird-server
    dockerfile: combined/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-server
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

  - id: anonbird-reverse-proxy
    ids:
      - anonbird-proxy
    dockerfile: proxy/Dockerfile
    images:
      - ghcr.io/cr0me1ve/anonbird-reverse-proxy
    tags:
      - "{{ .Version }}"
      - latest
    labels: *oci_labels
    platforms: *linux_platforms

checksum:
  extra_files:
    - glob: ./infrastructure_files/getting-started-with-zitadel.sh
    - glob: ./release_files/install.sh
    - glob: ./infrastructure_files/getting-started.sh

release:
  prerelease: auto
  extra_files:
    - glob: ./infrastructure_files/getting-started-with-zitadel.sh
    - glob: ./release_files/install.sh
    - glob: ./infrastructure_files/getting-started.sh
