FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY client ./client
COPY dns ./dns
COPY encryption ./encryption
COPY flow ./flow
COPY formatter ./formatter
COPY monotime ./monotime
COPY proxy ./proxy
COPY route ./route
COPY shared ./shared
COPY sharedsock ./sharedsock
COPY upload-server ./upload-server
COPY util ./util
COPY version ./version
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o anonbird-proxy ./proxy/cmd/proxy

RUN echo "anonbird:x:1000:1000:anonbird:/var/lib/anonbird:/sbin/nologin" > /tmp/passwd && \
    echo "anonbird:x:1000:anonbird" > /tmp/group && \
    mkdir -p /tmp/var/lib/anonbird && \
    mkdir -p /tmp/certs

FROM gcr.io/distroless/base:debug
COPY --from=builder /app/anonbird-proxy /usr/bin/anonbird-proxy
COPY --from=builder /tmp/passwd /etc/passwd
COPY --from=builder /tmp/group /etc/group
COPY --from=builder --chown=1000:1000 /tmp/var/lib/anonbird /var/lib/anonbird
COPY --from=builder --chown=1000:1000 --chmod=755 /tmp/certs /certs
USER anonbird:anonbird
ENV HOME=/var/lib/anonbird
ENV NB_PROXY_ADDRESS=":8443"
EXPOSE 8443
ENTRYPOINT ["/usr/bin/anonbird-proxy"]
