FROM golang:1.26.4-bookworm AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOMAXPROCS=1 CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/anonbird-relay ./relay

FROM gcr.io/distroless/base-debian12:nonroot
ENTRYPOINT ["/usr/local/bin/anonbird-relay"]
ENV NB_LOG_FILE=console
CMD ["--listen-address", ":33080", "--health-listen-address", ":9000"]
COPY --from=builder /out/anonbird-relay /usr/local/bin/anonbird-relay
